#!/bin/bash

if [ $(whoami) != "root" ];
then
    echo "You need to be a root user in order to execute this command.";
    echo "Command Usage : sudo ConnectifyLinux start|stop";
    exit 1;
fi

if [ "$1" == "start" ]
then
	hostapdPID=`ps -C hostapd --no-heading | sed -e 's/^ *//g' -e 's/ *$//g' | cut -d ' ' -f 1`
	if [ -z "$hostapdPID" ]
	then
		/usr/share/ConnectifyLinux/startConnectifyLinux & disown
	else
		echo "ConnectifyLinux already running.";
	fi
elif [ "$1" == "stop" ]
then
	hostapdPID=`ps -C hostapd --no-heading | sed -e 's/^ *//g' -e 's/ *$//g' | cut -d ' ' -f 1`
    if [ -z "$hostapdPID" ]
    then
        echo "ConnectifyLinux not running";
    else
        /usr/share/ConnectifyLinux/stopConnectifyLinux & disown
    fi
else
	echo "Enter a valid option : start or stop."
fi
