#!/bin/bash

if [ $(whoami) != "root" ];
then
    echo "You need to be a root user in order to execute this command.";
    echo "Command Usage : sudo ConnectifyLinux stop";
    exit 1;
fi

hostapdPID=`ps -C hostapd --no-heading | sed -e 's/^ *//g' -e 's/ *$//g' | cut -d ' ' -f 1`
kill -9 $hostapdPID
